# Generated by Django 4.0.3 on 2023-07-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
