# Generated by Django 4.0.3 on 2023-07-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_sale_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sold',
            field=models.BooleanField(default=True),
        ),
    ]
