# Generated by Django 4.0.3 on 2023-07-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_alter_sale_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sold',
        ),
    ]
