# Generated by Django 4.0.3 on 2023-07-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_appointment_date_time_appointment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='employee_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
